# Generated by Django 3.2.8 on 2021-10-09 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211009_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='dataset_id',
        ),
        migrations.AddField(
            model_name='dataset',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='dataset',
            name='price_per_feature',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dataset',
            name='price_per_row',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
    ]
