# Generated by Django 3.2.8 on 2021-10-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dataset_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='type',
            field=models.IntegerField(choices=[(0, 'Приватный'), (1, 'Публичный')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.IntegerField(choices=[(0, 'В обработке'), (1, 'Готов')]),
        ),
    ]
