# Generated by Django 3.2.8 on 2021-10-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211009_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='analytics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='price_per_feature',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='price_per_row',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'В обработке'), (1, 'Готов')], null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='dataset_tags', to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Приватный'), (1, 'Публичный')], null=True),
        ),
    ]
