version: '3'

services:
  web:
    # Берем Dockerfile из каталога app
    build: .
    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:7000
    # куда будут помещены данные из каталога app
    volumes:
      - ./app/:/usr/src/app/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 7000:7000
    # Файл содержащий переменные для контейнера